

services:

    frontend:
        container_name: frontend
        build:
          context: ./deployment/frontend/
        restart:  unless-stopped
        volumes:
          - ./frontend:/app
        ports:
          - "3000:3000"
        # depends_on:
        #   - backend
        env_file:
          - .env

    # backend:
    #     container_name: backend

    #     build:
    #       context: ./deployment/backend/
    #     restart: unless-stopped
    #     volumes:
    #       - ./backend:/app
    #     depends_on:
    #       - redis
    #     ports:
    #       - 8000:8000
    #     env_file:
    #       - .env
        
    # redis:
    #     container_name: redis
    #     build: ./deployment/redis/
    #     restart: unless-stopped

    # nginx:
    #     container_name: nginx
    #     build:
    #       context: ./deployment/nginx/
    #     restart: unless-stopped
    #     volumes:
    #       - /var/log/nginx/
    #     env_file:
    #       - .env
    #     depends_on:
    #       - frontend
    #       - backend
    #     ports:
    #       - "4433:443"