

services:

    postgresql:
        container_name: postgresql
        image: postgres:15-alpine
        environment:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./postgresql-logs:/var/log/postgresql
        restart: unless-stopped

    frontend:
        container_name: frontend
        build:
          context: ./frontend/vite_project
        restart:  unless-stopped
        volumes:
          - ./frontend/vite_project/src:/app/src
          - ./frontend/vite_project/public:/app/public
        ports:
          - "5173:5173"
        env_file:
          - .env

    backend:
        container_name: backend
        build:
          context: ./backend/core
        restart: unless-stopped
        volumes:
          - ./backend/core:/app/core
        ports:
          - 8000:8000
        env_file:
          - .env
        depends_on:
          - postgresql
            
        
    redis:
        container_name: redis
        build: ./deployment/redis
        volumes:
          - ./redis-logs:/data
        ports:
          - "6380:6379"
        restart: unless-stopped

    nginx:
        container_name: nginx
        build:
          context: ./deployment/nginx
        restart: unless-stopped
        volumes:
          - ./nginx-logs:/var/log/nginx/
        env_file:
          - .env
        depends_on:
          - frontend
          - backend
        ports:
          - "8443:443"

volumes:
  postgres_data: