

services:

    frontend:
        container_name: frontend
        build:
          context: ./frontend/vite_project
        restart:  unless-stopped
        volumes:
          - ./frontend/app:/app
        ports:
          - "5173:5173"
        env_file:
          - .env

    backend:
        container_name: backend

        build:
          context: ./backend/core
        restart: unless-stopped
        volumes:
          - ./backend/app:/app
        ports:
          - 8000:8000
        env_file:
          - .env
        
    redis:
        container_name: redis
        build: ./deployment/redis
        volumes:
          - ./redis-logs:/data
        ports:
          - "6379:6379"
        restart: unless-stopped

    nginx:
        container_name: nginx
        build:
          context: ./deployment/nginx
        restart: unless-stopped
        volumes:
          - ./nginx-logs:/var/log/nginx/
        env_file:
          - .env
        depends_on:
          - frontend
          - backend
        ports:
          - "443:443"