# Generated by Django 5.1.7 on 2025-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0002_alter_chatroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Private Chat'), ('general', 'General Chat')], default='public', max_length=10),
        ),
    ]
