# Generated by Django 5.1.7 on 2025-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0003_alter_chatroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('general', 'General Chat'), ('private', 'Private Chat')], default='public', max_length=10),
        ),
    ]
