# Generated by Django 5.1.7 on 2025-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0006_invitation_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status_choice',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
