# Generated by Django 5.1.7 on 2025-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0007_alter_invitation_status_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('general', 'General Chat'), ('private', 'Private Chat')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('invite', 'Invitation')], max_length=10),
        ),
    ]
