# Generated by Django 5.1.7 on 2025-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0008_alter_chatroom_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Private Chat'), ('general', 'General Chat')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status_choice',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
