# Generated by Django 5.1.7 on 2025-05-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0011_alter_chatroom_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status_choice',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('invite', 'Invitation')], max_length=10),
        ),
    ]
